### ISSUE TITLE
confusion：Get the details

### ISSUE THREAD

**Issue by runnerSnail** [jspm/generator.jspm.io#1]
Dude, your project is great
## question
> I would like to know about how this request is implemented behind ，I don't know if you open source this part
[getExports](https://github.com/jspm/generator/blob/31f30316e6de463ca3b1329ebc80e428f1f31fa8/src/api.js#L132)
[getVersions](https://github.com/jspm/generator/blob/31f30316e6de463ca3b1329ebc80e428f1f31fa8/src/api.js#L119)

## At the end

Thank you for your answer！

**Comment by guybedford** [comment]
Thanks! So the code that handles these functions is part of the API library for JSPM which is actually itself still in a private beta release.

If you'd like access to this codebase directly you can join the beta on Discord here - https://discord.gg/dNRweUu.

**Comment by guybedford** [comment]
The base project which is used to do the work for the online generator now fully open source and available at https://github.com/jspm/generator.
