### ISSUE TITLE
Drag and drop issue

### ISSUE THREAD

**Issue by guybedford** [jspm/generator.jspm.io#10]
Getting a "Failed in reading file content" in the toast on the website when trying to drag and drop.

//cc @JayaKrishnaNamburu

**Comment by Bubblyworld** [comment]
Root error seems to be an issue with the entrypoints for `npm:stream-to-it@0.2.4`:

```
Error: No './source.js' exports subpath defined in https://ga.jspm.io/npm:stream-to-it@0.2.4/ resolving stream-to-it/source.js imported from https://ga.jspm.io/npm:ipfs-http-client@59.0.0/src/index.js.
```

I'm not sure on the details of the subpaths stuff we talked about on friday (though I'll be reading that code today!), but it sounds like we need an override for that package? Here are the exports that the CDN picks up automatically:

```
"exports": {
    ".": "./index.js",
    "./source": "./source.js",
    "./index.js!cjs": "./index.js",
    "./source.js!cjs": "./source.js"
  }
```

**Comment by Bubblyworld** [comment]
And on the `generator.jspm.io` side I'll see if I can make the error more obvious (it's not actually a "failed in reading file content").

**Comment by JayaKrishnaNamburu** [comment]
Thanks for correcting the error message @Bubblyworld
