### ISSUE TITLE
Importmap Generator: TypeError: this.processJSONFile is not a function

### ISSUE THREAD

**Issue by trusktr** [jspm/generator.jspm.io#38]
Steps to reproduce:

- click upload button
- choose a package.json file
- see console

```
Uncaught (in promise) TypeError: this.processJSONFile is not a function
    at input.onchange (mapapp.js?1:109:14)
```

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/generator.jspm.io/commit/b72b4d264bd9ef0edab26228ff59f8001e211bdf, to be published shortly.
