### ISSUE TITLE
Importmap Generator: not generating, `ReferenceError: url is not defined`

### ISSUE THREAD

**Issue by trusktr** [jspm/generator.jspm.io#39]
https://generator.jspm.io/#U2VnYGBkDM0rySzJSU1hyCnNTXUw0DPWM9BNzCnISNQzsgAAtDutDCIA

**Comment by guybedford** [comment]
Thanks for posting, fixed in https://github.com/jspm/generator.jspm.io/commit/71ae1f7b5ad7a07a8e3aebb0b0f38cd7378a31a8. Will publish shortly.
